# templates/servicemonitor.yaml
{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "django-app.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "django-app.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
{{- end }}
